In [6]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(y):
    return y * (1 - y)

X = np.array([[0, 0, 0, 1]])
y = np.array([[0]])

lr = 0.8
tolerance = 0.001
W1 = np.array([
    [ 0.3, 0.1],
    [-0.2, 0.4],
    [ 0.2, -0.3],
    [ 0.1, 0.4]
])
b1 = np.array([[0.2, 0.1]])

W2 = np.array([
    [-0.3],
    [ 0.2]
])
b2 = np.array([[-0.3]])

epoch = 0
first_epoch_printed = False

while True:
    epoch += 1

    z1 = np.dot(X, W1) + b1
    h = sigmoid(z1)

    z2 = np.dot(h, W2) + b2
    o = sigmoid(z2)
    error = y - o

    delta_out = error * sigmoid_derivative(o)
    delta_hidden = delta_out.dot(W2.T) * sigmoid_derivative(h)
    W2 += lr * h.T.dot(delta_out)
    b2 += lr * delta_out
    W1 += lr * X.T.dot(delta_hidden)
    b1 += lr * delta_hidden

    if not first_epoch_printed:
        print("\n--- First Epoch ---")
        print("Output (O):", o)
        print("Error (D - O):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        first_epoch_printed = True

    if abs(error[0][0]) < tolerance:
        print(f"\n--- Last Epoch (Converged at Epoch {epoch}) ---")
        print("Output (O):", o)
        print("Error (D - O):", error)
        print("Updated W1:\n", W1)
        print("Updated b1:\n", b1)
        print("Updated W2:\n", W2)
        print("Updated b2:\n", b2)
        break


--- First Epoch ---
Output (O): [[0.4139061]]
Error (D - O): [[-0.4139061]]
Updated W1:
 [[ 0.3         0.1       ]
 [-0.2         0.4       ]
 [ 0.2        -0.3       ]
 [ 0.10589097  0.39622458]]
Updated b1:
 [[0.20589097 0.09622458]]
Updated W2:
 [[-0.34614317]
 [ 0.14999979]]
Updated b2:
 [[-0.38032687]]

--- Last Epoch (Converged at Epoch 234766) ---
Output (O): [[0.001]]
Error (D - O): [[-0.001]]
Updated W1:
 [[ 0.3         0.1       ]
 [-0.2         0.4       ]
 [ 0.2        -0.3       ]
 [ 0.81972512  0.86331884]]
Updated b1:
 [[0.91972512 0.56331884]]
Updated W2:
 [[-2.42607592]
 [-1.87024235]]
Updated b2:
 [[-3.33497585]]
